//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP_furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoSuuTap
    {
        public int ID { get; set; }
        public string HinhAnhBST { get; set; }
        public string TenBST { get; set; }
        public string MoTaBST { get; set; }
        public string MoTaDai { get; set; }
        public string HinhAnh1 { get; set; }
        public string HinhAnh2 { get; set; }
        public string HinhAnh3 { get; set; }
    }
}
