//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP_furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuaHang360
    {
        public int ID { get; set; }
        public string TenCamHung { get; set; }
        public string Video1 { get; set; }
        public string Video2 { get; set; }
    }
}
