//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP_furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int ID { get; set; }
        public Nullable<int> ID_KhachHang { get; set; }
        public Nullable<int> ID_SanPham { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<int> SoLuongSanPham { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
