//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP_furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GocCamHung
    {
        public int ID { get; set; }
        public string TenCamHung1 { get; set; }
        public string MoTaCamHung1 { get; set; }
        public string HinhAnhCamHung1 { get; set; }
        public string TenCamHung2 { get; set; }
        public string MoTaCamHung2 { get; set; }
        public string HinhAnhCamHung2 { get; set; }
        public string TenCamHung3 { get; set; }
        public string MoTaCamHung3 { get; set; }
        public string HinhAnhCamHung3 { get; set; }
        public string HinhAnhEnd { get; set; }
    }
}
