//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP_furniture.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_QuanLyCuaHangDoNoiThatEntities : DbContext
    {
        public DB_QuanLyCuaHangDoNoiThatEntities()
            : base("name=DB_QuanLyCuaHangDoNoiThatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual DbSet<ChucNang> ChucNang { get; set; }
        public virtual DbSet<DonHang> DonHang { get; set; }
        public virtual DbSet<GioHang> GioHang { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPham { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyen { get; set; }
        public virtual DbSet<SanPham> SanPham { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoanAdmin> TaiKhoanAdmin { get; set; }
        public virtual DbSet<BoSuuTap> BoSuuTap { get; set; }
        public virtual DbSet<ThietKeNoiThat> ThietKeNoiThat { get; set; }
        public virtual DbSet<Phong> Phong { get; set; }
        public virtual DbSet<LoaiPhong> LoaiPhong { get; set; }
        public virtual DbSet<CuaHang360> CuaHang360 { get; set; }
        public virtual DbSet<GocCamHung> GocCamHung { get; set; }
        public virtual DbSet<GuiYeuCauHoTro> GuiYeuCauHoTro { get; set; }
        public virtual DbSet<TrangThai> TrangThai { get; set; }
    }
}
