//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP_furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int ID { get; set; }
        public Nullable<int> ID_NhanVien { get; set; }
        public Nullable<int> ID_ChucNang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ChucNang ChucNang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
