//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP_furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public int ID { get; set; }
        public string HinhAnhPhongKhach { get; set; }
        public string TenPhongKhach { get; set; }
        public Nullable<int> ID_LoaiPhong { get; set; }
        public string Mt1 { get; set; }
        public string Mt2 { get; set; }
        public string Mt3 { get; set; }
        public string Mt4 { get; set; }
        public string HinhAnh1 { get; set; }
        public string HinhAnh2 { get; set; }
        public string HinhAnh3 { get; set; }
        public string MoTaDai { get; set; }
    
        public virtual LoaiPhong LoaiPhong { get; set; }
    }
}
