//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP_furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.GioHang = new HashSet<GioHang>();
        }
    
        public int ID { get; set; }
        public string TenSanPham { get; set; }
        public string MoTaSanPham { get; set; }
        public Nullable<double> GiaSanPham { get; set; }
        public Nullable<int> SoLuongTonKho { get; set; }
        public string HinhAnhSanPham { get; set; }
        public Nullable<int> ID_LoaiSanPham { get; set; }
        public string HinhAnhSanPham2 { get; set; }
        public Nullable<int> Sale { get; set; }
        public Nullable<double> GiaSanPhamSale { get; set; }
        public string HinhAnhSanPham3 { get; set; }
        public string HinhAnhSanPham4 { get; set; }
        public string HinhAnhSanPham5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHang { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
